import React from 'react';
import { useAppContext } from '../context/AppContext';
import { AlertTriangle, AlertCircle, CheckCircle } from 'lucide-react';

export default function Alerts() {
  const { alerts } = useAppContext();

  return (
    <div className="flex flex-col h-full">
      <div className="mb-6">
        <h1 className="text-2xl font-semibold text-white">System Alerts</h1>
        <p className="text-slate-400 mt-1">Automated warnings generated by the Threshold Logic</p>
      </div>

      <div className="bg-neutral-900 border border-neutral-800 rounded-lg flex-1 overflow-hidden flex flex-col">
        <div className="overflow-x-auto">
          <table className="w-full text-sm text-left text-slate-400">
            <thead className="text-xs text-slate-300 uppercase bg-[#0f172a] border-b border-neutral-800">
              <tr>
                <th className="px-6 py-4">Severity</th>
                <th className="px-6 py-4">Timestamp</th>
                <th className="px-6 py-4">Device ID</th>
                <th className="px-6 py-4">Message</th>
                <th className="px-6 py-4">Status</th>
              </tr>
            </thead>
            <tbody>
              {alerts.length === 0 ? (
                <tr><td colSpan={5} className="px-6 py-12 text-center text-slate-500">No alerts triggered yet.</td></tr>
              ) : (
                alerts.map((alert, i) => (
                  <tr key={i} className="border-b border-neutral-800 hover:bg-neutral-800">
                    <td className="px-6 py-4">
                      {alert.severity === 'critical' ? (
                        <span className="flex items-center gap-2 text-red-500 font-bold uppercase"><AlertTriangle size={16}/> {alert.severity}</span>
                      ) : (
                        <span className="flex items-center gap-2 text-amber-500 font-bold uppercase"><AlertCircle size={16}/> {alert.severity}</span>
                      )}
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap">{new Date(alert.timestamp * 1000).toLocaleString()}</td>
                    <td className="px-6 py-4 font-medium text-white">{alert.device_id}</td>
                    <td className="px-6 py-4">{alert.message}</td>
                    <td className="px-6 py-4"><span className="px-3 py-1 bg-slate-800 rounded-full text-xs">Active</span></td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}
